### ISSUE TITLE
May I ask what should we do after running the file train.py?

### ISSUE THREAD

**Issue by YXW249** [Ls-Dai/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-PyTorch#3]
It seems a good project. Thanks for your work! I want to know how to use each file and the process/order of running the py files. Thanks again.

**Comment by Ls-Dai** [comment]
Hi, sorry for late reply. Firstly run rl.py for deep reinforcement learning training. Then use run_naive.py to start a chat bot test. Good luck!

**Comment by Ls-Dai** [comment]
> It seems a good project. Thanks for your work! I want to know how to use each file and the process/order of running the py files. Thanks again.

Hi, sorry for late reply. Firstly run rl.py to train a deep reinforcement learning model. Then use run_naive.py to start a chat box test. Good luck.
