### ISSUE TITLE
No meaningful dialogue

### ISSUE THREAD

**Issue by NA-E** [Ls-Dai/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-PyTorch#5]
Hello! May I know what can we expect from the bot? I am getting the following meaningless replies:
> how are you
Bot: tim tim .maybe .maybe spin serves serves deductible challenging challenging little little fridge cop resume
> well
Bot: quit quit figured keith keith biography biography biography biography taxis lover lover keith keith biography

**Comment by kuanyuchen123** [comment]
Same here, I first ran trian.py, then ran python rl.py, then loaded the weights into naive_run.py, and is getting meaningless replies. Not sure which part went wrong.

**Comment by yanmingl** [comment]
I faced the same problem. Anything update?

**Comment by Ls-Dai** [comment]
Sorry for late reply. Should you have any questions about this repo, feel free to dm me. There is a right copy.
